### ISSUE TITLE
Failed to match multiline import. 

### ISSUE THREAD

**Issue by jeaubin** [MyPingO/staircase-imports#1]
I have imports which goes over multi lines - and it reports this error

Failed to match multiline import. Please report this issue on the extension GitHub page!

To reproduce it

```
from bla.resources import (
    Device,
)
```

**Comment by MyPingO** [comment]
Hi, thanks for the report!
I'm pushing a hotfix for this now, please update the extension in 10 minutes!

**Comment by jeaubin** [comment]
Works - Thanks
